apiVersion: apps/v1
kind: Deployment
metadata:
  name: openweather-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openweather-service
  template:
    metadata:
      labels:
        app: openweather-service
    spec:
      imagePullSecrets:
        - name: arearegistrykey
      containers:
      - name: openweather-container
        image: julesreyn/area:openweather
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: WEATHER_KEY
          valueFrom:
            secretKeyRef:
              name: openweather-secret
              key: apikeyopenweather