apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      imagePullSecrets:
        - name: arearegistrykey
      containers:
      - name: sms-container
        image: julesreyn/area:sms
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: TWILIO_AUTH_TOKEN