apiVersion: v1
kind: Service
metadata:
  name: {{service}}-service
spec:
  selector:
    app: {{service}}-service
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{targetPort}}
  type: ClusterIP
